before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64

nfpms:
  - maintainer: &author
      Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description
      Amazon EC2 Hostname Setter
    license: &license
      Apache 2.0
    homepage: &homepage
      https://github.com/mvisonneau/ahs
    vendor: *author
    formats:
      - deb
      - rpm

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  skip: true
